### ISSUE TITLE
Wrong site link

### ISSUE THREAD

**Issue by reader-man** [drungrin/Fabric.Sdk.Xamarin#1]
Hi,
Thanks for the great project.

I wanted to report to you that in the page:
https://www.nuget.org/packages/Crashlytics.Sdk/2.5.5-alpha1

the link [Project Site] is linked to:
https://github.com/Drungrin/Fabric.SDK-Xamarin

which is wrong or does not work, and maybe you mean:
https://github.com/drungrin/Fabric.Sdk.Xamarin

the difference in the two links is a "-" instead of a "-".

**Comment by drungrin** [comment]
Thanks, fixed in the new packages.
