### ISSUE TITLE
Cannot get Answers to work with iOS

### ISSUE THREAD

**Issue by gviddy** [drungrin/Fabric.Sdk.Xamarin#10]
First off let me say thanks for creating these bindings. Fabric works awesome and it is great we can use it with Xamarin Forms. :)

Everything works perfectly on Xamarin Android. Crashes, Answers, etc. Perfect!

I am however having some issues with iOS and I did note that you mentioned you cannot use Answers and Crashlytics together on iOS. Why is this as it works fine together on Android?

If I include Answers as a reference in my iOS project then I get the following compile error:
`C:\Program Files (x86)\MSBuild\Xamarin\iOS\Xamarin.iOS.Common.targets(681,3): error : Could not register the assembly 'CrashlyticsKit.Platform': error MT4118: Cannot register two managed types ('Bindings.AnswersKit.Answers, CrashlyticsKit.Platform' and 'Bindings.AnswersKit.Answers, AnswersKit.Platform') with the same native name ('Answers').`

You mention that Crashlytics contains Answers so I then remove the reference from my iOS project, which then compiles fine, and instead get this exception when I try to log with Answers in my App:
`AnswersKit.AnswersPlatformNotSupportedException: The PCL build of Answers is being linked which probably means you need to use NuGet or otherwise link a platform-specific Answers.Platform.dll to your main application.`

I guess here it is complaining because Answers is no longer being referenced in the iOS project. So do you have a solution at all so that I can log using Answers? Android has no problems whatsoever and works fine. It would be great if iOS could do the same thing.

thanks!

**Comment by drungrin** [comment]
- Uninstall the packages
- Remove the references on References\From Packages on Xamarin
- Install The packages.

Xamarin mess with those references.

**Comment by gviddy** [comment]
**Remove the references on References\From Packages on Xamarin**

Sorry but I do not understand what you mean by this.

**Comment by gviddy** [comment]
Oh I finally got this working. In the iOS project if I include AnswersKit and AnswersKit.Platform from the Crashlytics folder then it works fine on iOS. Awesome!

**Comment by brittonbeckham** [comment]
@gviddy I'm having a similar issue, but including the assemblies from the Crashlytics folder is not fixing it. 

`System.Exception: Could not create an native instance of the type 'Bindings.AnswersKit.Answers': the native class hasn't been loaded.`

This error occurs the first time I run any code with `Answers.Instance...`

**Comment by gviddy** [comment]
Do you have this in your AppDelegate.cs ??

`// Fabric
 Crashlytics.Instance.Initialize();

 Fabric.Instance.Debug = true;
 Fabric.Instance.Initialize();`

**Comment by brittonbeckham** [comment]
So my app delegate looks like this: 

``` c#
public override bool FinishedLaunching(UIApplication application, NSDictionary launchOptions)
{
    Crashlytics.Instance.Initialize();
    Fabric.Instance.Initialize();

    AppDomain.CurrentDomain.UnhandledException += CurrentDomain_UnhandledException;


    Forms.Init();
    ImageCircleRenderer.Init();
    LoadApplication(new App.App());

    return base.FinishedLaunching(application, launchOptions);
}

```

I removed the `Fabric.Instance.Debug = true;` line because if I leave it it, it also blows up with a 
`System.NullReferenceException: Object reference not set to an instance of an object` error.

**Comment by teracat** [comment]
@brittonbeckham Are you trying it in the iOS simulator? If so, that is the problem. You'll have to try it on a real device. I have an implementation for every project to call the "Answers.Instance.Log..." and in the iOS implementation I do the following check:

`if (ObjCRuntime.Runtime.Arch == ObjCRuntime.Arch.DEVICE)
  Answers.Instance.Log...`

Hope this helps.

**Comment by brittonbeckham** [comment]
I am running it on a simulator... I will attempt it on a device to double check. Thanks for the input.
