### ISSUE TITLE
Package cannot be installed

### ISSUE THREAD

**Issue by danielbigler** [drungrin/Fabric.Sdk.Xamarin#11]
When trying to install the package to my PCL Project I receive the following error: 

> Severity  Code    Description Project File    Line    Suppression State
> Error       Could not install package 'Fabric 1.0.0'. You are trying to install this package into a project that targets '.NETPortable,Version=v4.5,Profile=Profile111', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

I am using Visual Studio 2015.

**Comment by drungrin** [comment]
Fixing the profile in the next version, coming out in a few days.

**Comment by stather** [comment]
Hi
Any chance of a new release with this fixed?
Thanks

**Comment by drungrin** [comment]
I have published a new nugget. 

Please check it.

**Comment by stather** [comment]
Hi.

Installed and all good. Thank you very much.
