### ISSUE TITLE
Digits package contains corrupted data

### ISSUE THREAD

**Issue by francescotonini** [drungrin/Fabric.Sdk.Xamarin#15]
Hi, I'd like to use this bindings on Xamarin.iOS and Xamarin.Android but according to NuGet (version 3.4.4), Digits package is corrupted. I tried to download the .nupkg file and install it from a local source but no luck, still the same problem. Does this happen to someone else?

![photo_2016-09-24_22-55-13](https://cloud.githubusercontent.com/assets/2104297/18811220/fdce7298-82a9-11e6-974a-c8017aa2002b.jpg)

**Comment by drungrin** [comment]
This is the kind of issue that should affect everyone. Try removing the package from the packages folder, and clearing all caches. I believe that is on your side.

**Comment by francescotonini** [comment]
I've tried to remove all packages but the problem remains. A collegue tried on his PC and the result was the same.

**Comment by franksweeney** [comment]
I am having the same problem as above, did you get a solution to it

**Comment by drungrin** [comment]
I have published a new nugget.

Please check it.

**Comment by franksweeney** [comment]
Yes that fixed the issue on my side. Thanks for your quick response
