### ISSUE TITLE
Theming and Authentication with mine backend

### ISSUE THREAD

**Issue by Lapinou42** [drungrin/Fabric.Sdk.Xamarin#17]
Hello, 

First of all, many thanks for your work. Indeed, I'm a iOS dev and I start my first Xamarin app and have to use Digits. 
But I noticed I can't theming Digits. But in the DigitsKit (on iOS and Android), it's possible.
How can I theming the Digits flow ? 
**Note**: https://docs.fabric.io/apple/digits/theming.html

And also, what about **authentication with your own backend** ?
I can't use this method to authenticate and verify user with my own backend: https://docs.fabric.io/apple/digits/advanced-setup.html#verifying-a-user

Thank you for your help,
Regards.

**Comment by drungrin** [comment]
You need to use the native bindings on the platform project, using the Bindings.\* packages.

The Update_Kits branch has more bindings for iOS, I'll upload the nuggets when I finish testing them.

**Comment by Lapinou42** [comment]
Okay, I'm gonna search about this because I don't know anything about Xamarin.
But, where should I find the Bindings.\* packages ? Should I do it all by myself or download them ? 

Thank you for your answer ;)

**Comment by drungrin** [comment]
Just install the nugget packages on the platform (iOs / Android) project. They aren't available on the PCL project.

**Comment by Lapinou42** [comment]
I installed the nugget packages already, yours I think. I'm using Xamarin forms. I install for now only for iOS project. Version 1.0.0.

Christophe Chantraine.

**Comment by Lapinou42** [comment]
But you have to update the nugget package on your side to have more bindings, right ? 

Or should I have to do something ?

Thank you for your precious help anyway !

**Comment by drungrin** [comment]
Right.

Or use the projects from Updated_Kits branch, either using the sources or building the packages.

I'll try to release the packages soon, I didn't got spare time this month.

**Comment by Lapinou42** [comment]
Ok I got it, don't worry ;)

2016-09-29 18:13 GMT+02:00 drungrin notifications@github.com:

**Comment by drungrin** [comment]
I have published a new nugget.

Please check it.

**Comment by Lapinou42** [comment]
Many thanks !!! I'll test it tomorrow morning :)

**Comment by Lapinou42** [comment]
Ok, I installed it just now : v1.1.0. 
What are the changes ? I can't see anything different between the v 1.0.0 and 1.1.0 version. Maybe I missed something ? 

Thank you anyway ! :)

**Comment by drungrin** [comment]
The kits were updated. 

My mistake, the bindings you need to  authentication with your own backend were already on 1.0.0 (https://github.com/drungrin/Fabric.Sdk.Xamarin/commit/af757456f889e8bc09882670075e1d1a5d960b81#diff-ced503a6143d57ad6bc0b5fcdc1f4ffa)

Are you missing any binding?

**Comment by Lapinou42** [comment]
Hmmm strange. So I probably missed something...
I'll check it tomorrow morning and I'll keep you informed.

**Comment by Lapinou42** [comment]
Ok, I checked it and indeed, I was using the wrong "using". 
I was using "using DigitsKit" instead of "using Bindings.DigitsKit" !

But I can't find how to set the DGTAuthenticationConfiguration to the "digits" instance:

![capture d ecran 2016-10-14 a 09 51 53](https://cloud.githubusercontent.com/assets/3692744/19379743/de59cd46-91f3-11e6-8bdb-fe9aa498c114.png)

Thank you :)

**Comment by drungrin** [comment]
You don't set. It is used as a parameter on the AuthenticateWithViewController and AuthenticateWithNavigationViewController methods.

It is explained on the link you provided, https://docs.fabric.io/apple/digits/theming.html

**Comment by Lapinou42** [comment]
I know, but I didn't find these methods. I have only the "Autenticate" method like above in my screenshot. I can't see AuthenticateWithViewController and AuthenticateWithNavigationViewController :/

**Comment by drungrin** [comment]
DigitsKit.Digits -> PCL Stuff, not all available. You should use that on PCL projects. DigitsKit.Digits.Instance.Authenticate() 'll work on both android and iOS.
Bindings.DigitsKit.Digits -> Native stuff, almost all of the fabric documentation is available. You should use that on Native projects.
All native bindings are below the Bindings namespace.

**Comment by Lapinou42** [comment]
Ok, I believe you, I probably made a mistake. 

I'm working with xamarin.ios and xamarin.droid, not xamarin.Forms.

I use Bindings.DigitsKit, not Bindings.DigitsKit.Digits, maybe it's because of that. I'm sorry for all that questions, it's my first Xamarin project and first use of C# language... 

Thank again.

**Comment by Lapinou42** [comment]
Hello, 

I see only one method even if I use Bindings.DigitsKit : 

![capture d ecran 2016-10-18 a 08 40 09](https://cloud.githubusercontent.com/assets/3692744/19467055/5c3c2c18-950f-11e6-8a30-2b11a9c6562e.png)

I can't find AuthenticateWithViewController or AuthenticateWithNavigationViewController methods.

**Comment by Lapinou42** [comment]
Oh my god. I had to use Digits.SharedInstance instead of DigitsKit.Digits.Instance ! 

Sorry ! You can close this issue :)

![capture d ecran 2016-10-18 a 08 57 04](https://cloud.githubusercontent.com/assets/3692744/19467342/fea593b2-9510-11e6-949f-b088b3cf2593.png)
