### ISSUE TITLE
Set callback for TwitterCore.Instance.LogIn

### ISSUE THREAD

**Issue by franksweeney** [drungrin/Fabric.Sdk.Xamarin#19]
Hi There, thanks for these bindings. I am trying to create login using twiyterCore (Digits already done thanks to sample provided.) but I am really struggling to create the callback required for TwitterCore.Instance.LogIn,  There is no setcallback on twitterLoginButton. You can actually assign to the the callback property but I cannot seem to create the callback as there is no Callback definition. Would you be able to point me in the right direction ? Thanks

**Comment by drungrin** [comment]
I'll need to check those bindings. They exists only as a dependency to Digits Kit.

**Comment by drungrin** [comment]
Fabric is deprecated and will be available until March 31, 2020. This project is also deprecated.
