### ISSUE TITLE
(Android) Bindings.FabricSdk.Services.Concurrency.UnmetDependencyException

### ISSUE THREAD

**Issue by Dids** [drungrin/Fabric.Sdk.Xamarin#21]
I can't seem to get the Android version running (iOS was easy). I've ran into all sorts of issues, and right now Answers is working, but I'm getting this exception with each launch:

```
Bindings.FabricSdk.Services.Concurrency.UnmetDependencyException: com.crashlytics.android.core.CrashlyticsMissingDependencyException: 
This app relies on Crashlytics. Please sign up for access at https://fabric.io/sign_up,
install an Android build tool and ask a team member to invite you to this app's organization.
```

Here's how I'm initializing:

```
            Crashlytics.Instance.Initialize();
#if DEBUG
            Fabric.Instance.Debug = true;
#endif
            Fabric.Instance.Initialize(this);
            Answers.Instance.LogCustom("Launch");
```

And here's my packages:

```
<package id="Answers" version="1.1" targetFramework="monoandroid70" />
<package id="Crashlytics" version="1.1" targetFramework="monoandroid70" />
<package id="Fabric" version="1.1" targetFramework="monoandroid70" />
```

FYI, I'm targeting Android API v24.

**Comment by drungrin** [comment]
As of readme:

> For crashlytics on android, there is a hidden configuration, you need to add/update the build id using a string resource
> 
> <string name="com.crashlytics.android.build_id">e9e6beb9c4284289ac68b9ab76a9ee56</string>

Please also check the samples projects, you should be missing something again, like https://github.com/drungrin/Fabric.Sdk.Xamarin/issues/20

**Comment by Dids** [comment]
Sorry, I'm not as familiar with Android as I should be (iOS dev, making the move to Xamarin).

Adding the string resource did indeed fix it, thank you!
