### ISSUE TITLE
Initialization order maters?

### ISSUE THREAD

**Issue by rudyryk** [drungrin/Fabric.Sdk.Xamarin#22]
I tried to make Fabric work with the following code:

``` csharp
#if DEBUG
Fabric.Instance.Debug = true;
#endif
Fabric.Instance.Initialize ();
Crashlytics.Instance.Initialize ();
```

but it didn't work. Also it didn't crash or display any suspicious debug output.

Finally, I just put `Crashlytics.Instance.Initialize ()` **before** `Fabric.Instance.Initialize ()`:

``` csharp
Crashlytics.Instance.Initialize ();
#if DEBUG
Fabric.Instance.Debug = true;
#endif
Fabric.Instance.Initialize ();
```

**Comment by drungrin** [comment]
Yes, after fabric is initialized, no kits are added. You need to initialize the kits before initializing fabric.

It is similar to calling Fabric.With multiple times on the native sdk, only the first one has effect.

**Comment by rudyryk** [comment]
> You need to initialize the kits before initializing fabric.

I see, thank you!

I think this part is unclear and it would be nice to have some notes on that in docs. And probably write warnings to console output on such attempts.
