### ISSUE TITLE
Unable to Add in PCL

### ISSUE THREAD

**Issue by chanti-github** [drungrin/Fabric.Sdk.Xamarin#23]
Hi drungrin,
when i am trying to add this package i am getting the following error. 
Could not install package 'Fabric 1.1'. You are trying to install this package into a project that targets 'portable-net45+win+wp80+MonoAndroid10+xamarinios10+MonoTouch10', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

i tried to download your sample solution in this solution also i am facing problems.

Can you please help me out on this.

Please Respond on this issue.

**Comment by drungrin** [comment]
Sorry about the delay.

Make sure that your project uses the PCL Profile111, which is the one used by Xamarin currently.

**Comment by chanti-github** [comment]
Thanks for reply but my PCL profile is 78 , can't we use this package ??

**Comment by drungrin** [comment]
I use the profile Xamarin actually uses on new projects.

https://developer.xamarin.com/guides/xamarin-forms/platform-features/windows/installation/#pcl

Why can't you use the 111?

There are some notes about Xamarin and PCL profiles:

http://danrigby.com/2014/04/16/xamarin-pcl-profile-notes/

**Comment by chanti-github** [comment]
i cannot use pcl 111 now because this project is running from so long if I
want to change it I don't know where it reflect and I don't want to change

Thanks,
Subbarao

**Comment by drungrin** [comment]
You can also build the solution and change in the nuspec to profile 78, then build the nugget. no code changes are needed besides the nuspec. It is a really simple process.

The official packages will follow whatever is default on new xamarin projects.
