### ISSUE TITLE
FabrikSDK dependency not resolved in sample forms project on IOS

### ISSUE THREAD

**Issue by Karuna30** [drungrin/Fabric.Sdk.Xamarin#24]
I am trying to run the sample forms project. I checked out the latest and to import projects I changed my project profile to 111. Had to retarget the packages and also update Xamarin Forms to 2.3.2.127.

After that I am not able to compile the IOS Project, Xamarin Studio is not able to resolve CrashlyticsKit and FabricSdk. For some reason DigitsKit is being resolved. Would really appreciate any pointers to resolve.

```
using CrashlyticsKit; << Error
using DigitsKit;
using FabricSdk;<< Error
```

**Comment by Awesometimes** [comment]
Not sure if you're still running into an issue or not, but I was able to get this to work by changing the project profile to something PCL 4.6 (e.g., Profile151 or Profile44)
