### ISSUE TITLE
Digits does not exists contructor

### ISSUE THREAD

**Issue by jeffersonsc** [drungrin/Fabric.Sdk.Xamarin#26]
Hello, im using xamarin digits in my projet, one error is appear when invoke new Digits

Fabric.With(this, new TwitterCore(authConfig), new Digits());

/Users/jefferson/Projects/investeapp31/investeapp31/MainActivity.cs(60,60): Error CS1540: Cannot access protected member `Bindings.DigitsKit.Digits.Digits(System.IntPtr, Android.Runtime.JniHandleOwnership)' via a qualifier of type `Bindings.DigitsKit.Digits'. The qualifier must be of type `investeapp31.MainActivity' or derived from it (CS1540) (investeapp31)

**Comment by kostwald** [comment]
you need to initialize it as 
Fabric.With(this, new TwitterCore(authConfig), new Digits.Builder().Build());
