### ISSUE TITLE
Support Profile259

### ISSUE THREAD

**Issue by homerokzam** [drungrin/Fabric.Sdk.Xamarin#27]
I'm having problems when trying to install the package in a Xamarin.Forms project.
Here is the error:
Could not install package 'Fabric 1.1.0'. You are trying to install this package into a project that targets '.NETPortable,Version=v4.5,Profile=Profile259', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

Thanks,
Homero

**Comment by pdecarcer** [comment]
You have to change the profile for the Profile111 and then retarget some packages

**Comment by drungrin** [comment]
Closing as the supported profile being the one of new xamarin projects.
