### ISSUE TITLE
Android crashes aren't readable

### ISSUE THREAD

**Issue by smadam** [drungrin/Fabric.Sdk.Xamarin#29]
Thanks for putting this library together!  

I'm using your library v1.1
I'm running Xamarin Studio with Xamarin.Android Version: 7.0.2.37
SDK Tools Version: 25.2.3
SDK Platform Tools Version: 25.0.1
SDK Build Tools Version: 23.0.3
JDK 1.8
Not using ProGuard or Multidex

On the Android side, when a crash report comes through to the Fabric dashboard, I do not see corresponding class names or line numbers within the crash report.   I don't see references to anything C#, just some java references.  

Is anyone else experiencing this?  Any advice on how to fix it?  Not having the info makes the crash indecipherable. 

Thanks again.

[MainActivitySample.txt](https://github.com/drungrin/Fabric.Sdk.Xamarin/files/642816/MainActivitySample.txt)

**Comment by drungrin** [comment]
Sorry about the delay. Can you provide some crash reports?

**Comment by smadam** [comment]
No worries at all.  Thank you for your response. Attached is the crash report that gets generated with the sample I attached earlier. 

[MainActivitySample_CrashReport.txt](https://github.com/drungrin/Fabric.Sdk.Xamarin/files/680146/MainActivitySample_CrashReport.txt)

**Comment by smadam** [comment]
@drungrin, any chance you've been able to take a look at this yet?  Anyone else out there able to chime in?

**Comment by drungrin** [comment]
In a release build, you'll not see line numbers.

The stack trace is correct,

at CrashlyticsTest.MainActivity+<OnCreate>c__AnonStorey0.<>m__0 (System.Object , System.EventArgs )(filename unknown)

Class: CrashlyticsTest.MainActivity
Method: OnCreate, on an anonymous method, receiving System.Object , System.EventArgs

The references are C#, note the CrashlyticsTest.MainActivity and System namespace.

**Comment by kiliman** [comment]
As of Xamarin.Android 7.3, you can now get filenames and line numbers in release builds. https://developer.xamarin.com/releases/android/xamarin.android_7/xamarin.android_7.3/#File_name_and_line_number_information_in_release_builds

However, there's a workaround for ensuring the proper stack trace is submitted to Crashlytics in order for the `mono-symbolicate` tool to work.

See issue #46
