### ISSUE TITLE
Sample code for using Digits?

### ISSUE THREAD

**Issue by muhaym** [drungrin/Fabric.Sdk.Xamarin#3]
Can you please explain how I can set call back for DigitsButton, so I can get Success and Failure events.

**Comment by muhaym** [comment]
in Xamarin.Android

**Comment by drungrin** [comment]
You can make your activity implements IAuthCallback

`public class MainActivity : AppCompatActivity, IAuthCallback`

then find the button and set it to use this as callback:

`var digitsButton = FindViewById<DigitsAuthButton>(Resource.Id.auth_button);
            digitsButton.SetCallback (this);`
