### ISSUE TITLE
Missing dSYM on Xamarin.iOS Project

### ISSUE THREAD

**Issue by feraask** [drungrin/Fabric.Sdk.Xamarin#30]
When I run my app and test a crash I am getting it reported to fabric but on the fabric.io website it says it is missing the dSYM files so I don't see any stack trace or anything. Am I missing some setup for an iOS project that is required?

I created an Xcode project and setup fabric there first then I added the following code to my AppDelagate.cs:
`NSObject[] fabricArray = {new Crashlytics()};
Fabric.With(fabricArray);`

I added the the necessary keys to my info.plist as well. I think the only thing that might be missing is that build script that runs in Xcode. I'm not sure how to transfer that to Xamarin. Is there more detailed instructions for setting this up?

**Comment by cnordvik** [comment]
Crashlytics has some docs on uploading them manually. I do this on TeamCity: 
Crashlytics/uploadSymbols <api key from crashlytics> ios MyApp/archive/MyApp.app.dSYM
