### ISSUE TITLE
Pls document: Crashlytics etc should work on iOS7 but this project requires iOS8

### ISSUE THREAD

**Issue by trevoriancox** [drungrin/Fabric.Sdk.Xamarin#31]
iOS7 support documented here https://docs.fabric.io/apple/supported-versions.html

However, Fabric.Sdk.Xamarin seems have an undocumented dependency on iOS8:

    /Users/trevorc/Documents/src/funtimes/FunTimesX/FunTimesX.iOS/MTOUCH: Error MT1305: The binding library 'FabricSdk.Platform.dll' contains a user framework (FabricSdk.Platform.dll), but embedded user frameworks require iOS 8.0 (the deployment target is Fabric.framework). Please set the deployment target in the Info.plist file to at least 8.0. (MT1305) (FunTimesX.iOS)

**Comment by drungrin** [comment]
I don't have control of the embedded frameworks. They are shipped as provided from twitter. Are you sure that the pod can target iOS 7?

**Comment by trevoriancox** [comment]
The problem could be on their end, but the fabric.io web page says:

> The table below shows the minimum supported versions of Xcode and OS for the latest Crashlytics, Digits, Twitter Kit, and MoPub SDKs.
> Crashlytics | iOS 7.0

https://docs.fabric.io/apple/supported-versions.html

The issue is "embedded user frameworks" but I don't know what the implications of that are.
