### ISSUE TITLE
Issues during Initialization

### ISSUE THREAD

**Issue by InfiniteCode** [drungrin/Fabric.Sdk.Xamarin#38]
For some reasons, integration doesn't work in my app.

Imported packages:
```
<package id="Crashlytics" version="1.1" targetFramework="xamarinios10" />
<package id="Fabric" version="1.1" targetFramework="xamarinios10" />
```

Info.plist:
```
<key>Fabric</key>
<dict>
	<key>APIKey</key>
	<string>ActualValidKeyHere</string>
</dict>
```

Initialization code:

```
Crashlytics.Instance.Initialize();
#if DEBUG
	Fabric.Instance.Debug = true;
#else
	Fabric.Instance.Debug = false;
#endif
Fabric.Instance.Initialize();
```

Then trying to log an exception:
```
Crashlytics.Instance.RecordException(new Exception("Test Exception"));
```

and it fails with the following stack trace:
System.ArgumentNullException
Value cannot be null.
Parameter name: str

>   at Foundation.NSString..ctor (System.String str) [0x0000c] in /Users/builder/data/lanes/3985/35d1ccd0/source/xamarin-macios/src/Foundation/NSString.cs:147 
>   at CrashlyticsKit.Crashlytics.RecordException (System.Exception exception) [0x0000b] in <15f0b4eeb6b3494eb22c04509ada3d80>:0 
>   at iOS.AppDelegate.FinishedLaunching (UIKit.UIApplication application, Foundation.NSDictionary launchOptions) [0x0002a] in /Users/Projects/iOS/AppDelegate.cs:52 
>   at (wrapper managed-to-native) UIKit.UIApplication:UIApplicationMain (int,string[],intptr,intptr)
>   at UIKit.UIApplication.Main (System.String[] args, System.IntPtr principal, System.IntPtr delegate) [0x00005] in /Users/builder/data/lanes/3985/35d1ccd0/source/xamarin-macios/src/UIKit/UIApplication.cs:79 
>   at UIKit.UIApplication.Main (System.String[] args, System.String principalClassName, System.String delegateClassName) [0x00038] in /Users/builder/data/lanes/3985/35d1ccd0/source/xamarin-macios/src/UIKit/UIApplication.cs:63 
>   at iOS.Application.Main (System.String[] args) [0x00008] in /Users/iOS/Main.cs:12 

Is something forgotten or messed up? Registration at Fabric is fine.

**Comment by drungrin** [comment]
Please make a repo with a sample project that has the issue, so I can investigate further.

**Comment by thedillonb** [comment]
I also hit this problem. However, I noticed that if I called `Crashlytics.Instance.Crash()` then it actually sent a crash to Fabric. So I'm not sure what it is with the `RecordException`...

**Comment by Ivan-L** [comment]
I am facing the same issue. There is no stack trace for the exception being logged, i.e. the StackTrace property is null. The RecordException method does not do a null check on that property and sends a null value to the NSString constructor, which causes the ArgumentNullException.
