### ISSUE TITLE
Crashlytics crash

### ISSUE THREAD

**Issue by Dimentar** [drungrin/Fabric.Sdk.Xamarin#40]
Hi,
Firs of all thanks for porting this library.

My question is: when you will able to update the Crashlytics, and other components?
Because of bug it's crashing on:

`[ANSWriteEventOperation logLineWithTimestamp:eventName:payloadDictionary:]`

The last version at this moment is 3.8.4
Thanks

**Comment by drungrin** [comment]
The version were updated on 1.2 release to

    "com.digitskit.sdk.ios" = "2.8.0";
    "com.twitter.answers.ios" = "1.3.4";
    "com.twitter.crashlytics.ios" = "3.8.4";
    "io.fabric.sdk.ios" = "1.6.11";

**Comment by Dimentar** [comment]
Thanks a lot +1
