### ISSUE TITLE
callback url and AuthConfig Builder for xamarin.forms application

### ISSUE THREAD

**Issue by Karuna30** [drungrin/Fabric.Sdk.Xamarin#41]
I have used your example to integrate digits with my xamarin.forms application.
I was reading about digits on its website and they have used some callback url  and AuthConfig Builder for their android application. But I am not able to find how to do same in xamarin.forms application. can you please help me?

**Comment by drungrin** [comment]
Fabric is deprecated and will be available until March 31, 2020. This project is also deprecated.
