### ISSUE TITLE
Documentation contradiction

### ISSUE THREAD

**Issue by chairmanMal** [drungrin/Fabric.Sdk.Xamarin#42]
The read file has a contradiction,

"In order to automate the process Crashlytics **has a plugin** for Android Studio (“AS”) that creates a UUID for a version.& build number when you make the project. Since there is **no plugin for AS**, ..."

Is there a plugin or not ??

**Comment by drungrin** [comment]
Since there is no plugin for XS

**Comment by chairmanMal** [comment]
Is this something that running a script either before or after the build in XS could accomplish in the manner of a plugin ?

Chris

**Comment by drungrin** [comment]
On iOS, Yes. For Android, you can decompile the AS plugin and check what it does.
