### ISSUE TITLE
Crashlytics crash

### ISSUE THREAD

**Issue by brunoracosta** [drungrin/Fabric.Sdk.Xamarin#45]
When my app throw a exception, the Crashlytics capture but it close the app:

I am using .Net Portable PCL 4.6 - Profile44 in a Visual Studio for MAC.

Output in MainActivity,cs OnCreate (I only took the name of the company):

> [Fabric] Build ID is: 853b46f4-c6ba-4ff1-....
[CrashlyticsCore] Initializing Crashlytics 2.3.16.dev
[CrashlyticsCore] Installer package name is: null
[CrashlyticsCore] Found previous crash marker.
[CrashlyticsCore] Exception handling initialization successful
[Fabric] Initializing io.fabric.sdk.android:fabric [Version: 1.3.16.dev], with the following kits:
[Fabric] com.crashlytics.sdk.android:answers [Version: 1.3.12.dev]
[Fabric] com.crashlytics.sdk.android:crashlytics [Version: 2.6.7.dev]
[Fabric] com.crashlytics.sdk.android:beta [Version: 1.2.4.dev]
[Fabric] com.crashlytics.sdk.android.crashlytics-core [Version: 2.3.16.dev]
[Fabric] 
[CrashlyticsCore] Opening a new session with ID 59933FC40193-0001-648A-5B94C780E476
[Beta] Beta device token present: false
[Fabric] Could not call getId on com.google.android.gms.ads.identifier.AdvertisingIdClient$Info
[Fabric] Could not call isLimitAdTrackingEnabled on com.google.android.gms.ads.identifier.AdvertisingIdClient$Info
[Fabric] Could not get parcel from Google Play Service to capture AdvertisingId
[Fabric] Could not get parcel from Google Play Service to capture Advertising limitAdTracking
[Fabric] AdvertisingInfo not present
[Fabric] Build ID is: 853b46f4-c6ba-4ff1-....
[Fabric] Build ID is: 853b46f4-c6ba-4ff1-....
[Fabric] Requesting settings from https://settings.crashlytics.com/spi/v2/platforms/android/apps/br.com./settings
[Fabric] Settings query params were: {icon_hash=a5b43d5263c0a48f354e4bfc86ce70ac266084dd, display_version=1.0, source=1, instance=8d6626afdec270f0d40360608ccc792fcf12fbed, build_version=1}
[Fabric] Settings result was: 200
[Fabric] Settings request ID: 6ed0d3f424e715a7....
[Fabric] Writing settings to cache file...
[Fabric] Loaded settings: {"settings_version":2,"cache_duration":7200,"features":{"collect_logged_exceptions":true,"collect_reports":true,"collect_analytics":true,"prompt_enabled":false,"push_enabled":true},"analytics":{"url":"https:\/\/e.crashlytics.com\/spi\/v2\/events","flush_interval_secs":120,"max_file_count_per_send":1,"track_custom_events":true,"track_predefined_events":true,"track_view_controllers":false,"flush_on_background":true,"max_byte_size_per_file":40000,"max_pending_send_file_count":20,"sampling_rate":1,"forward_to_google_analytics":false,"include_purchase_events_in_forwarded_events":false},"beta":{"update_suspend_duration":1800,"update_endpoint":"https:\/\/api.crashlytics.com\/spi\/v2\/platforms\/android\/apps\/br.com.\/beta_update_check"},"app":{"identifier":"br.com.","status":"activated","url":"https:\/\/api.crashlytics.com\/spi\/v1\/platforms\/android\/apps\/br.com.,"reports_url":"https:\/\/reports.crashlytics.com\/spi\/v1\/platforms\/android\/apps\/br.com.\/reports","update_required":false},"session":{"log_buffer_size":64000,"max_chained_exception_depth":16,"max_complete_sessions_count":4,"max_custom_exception_events":8,"max_custom_key_value_pairs":64,"identifier_mask":255},"prompt":{"title":"Send Crash Report?","message":"Looks like we crashed! Please help us fix the problem by sending a crash report.","send_button_title":"Send","show_cancel_button":true,"cancel_button_title":"Don't Send","show_always_send_button":true,"always_send_button_title":"Always Send"},"expires_at":1502829560947}
[Fabric] Build ID is: 853b46f4-c6ba-4ff1-....
[Beta] Beta kit initializing...
[Beta] Beta device token present: false
[Beta] A Beta device token was not found for this app
[Answers] Analytics collection enabled
[CrashlyticsCore] Initialization marker file created.
[Answers] Custom event tracking enabled
[Answers] Predefined event tracking enabled
[CrashlyticsCore] Finalizing previously open sessions.
[CrashlyticsCore] Closing open sessions.
[CrashlyticsCore] Closing session: 59933DA90177-0002-5DDA-...
[CrashlyticsCore] Collecting session parts for ID 59933DA90177-0002-5DDA-..
[CrashlyticsCore] Session 59933DA90177-0002-5DDA-.. has fatal exception: false
[CrashlyticsCore] Session 59933DA90177-0002-5DDA-.. has non-fatal exceptions: false
[CrashlyticsCore] No events present for session ID 59933DA90177-0002-5DDA-5B94C780E476
[CrashlyticsCore] Removing session part files for ID 59933DA90177-0002-5DDA-5B94C780E476
[CrashlyticsCore] Closed all previously open sessions
[CrashlyticsCore] Starting report processing in 1.0 second(s)...
[CrashlyticsCore] Initialization marker file removed: true
[Answers] Sending 1 analytics files to https://e.crashlytics.com/spi/v2/events
[Answers] Response code for analytics file send is 200
[CrashlyticsCore] Checking for crash reports...
[CrashlyticsCore] No reports found.

And When throw a Exception:

> [CrashlyticsCore] Crashlytics is handling uncaught exception "null" from thread Thread-7283

**Comment by StianCronje** [comment]
Did you find a solution?

**Comment by iorikingdom** [comment]
+1

**Comment by drungrin** [comment]
Fabric is deprecated and will be available until March 31, 2020. This project is also deprecated.
