### ISSUE TITLE
java.lang.NullPointerException in your plugin 1.1 and 1.4 versions

### ISSUE THREAD

**Issue by devbbras** [drungrin/Fabric.Sdk.Xamarin#48]
Hi there,

I' am trying to implement your plugin in my project, but I have a problem.
The First time that I run my program, It works fine, but the second time that I run, It crashs.
Here, I will paste code that I implement, in MainActivity.cs:
```
            Crashlytics.Instance.Initialize();
            Fabric.Instance.Debug = true;
            Fabric.Instance.Initialize(this);
```
When I comment this lines of code, the program is stable.

I will paste, the output message:
### 10-16 12:12:57.552 D/CrashlyticsCore(17187): Crashlytics is handling uncaught exception "null" from thread Thread-1807
10-16 12:12:57.562 E/CrashlyticsCore(17187): An error occurred in the fatal exception logger
10-16 12:12:57.562 E/CrashlyticsCore(17187): java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Class java.lang.Object.getClass()' on a null object reference
10-16 12:12:57.562 E/CrashlyticsCore(17187): 	at com.crashlytics.android.core.CrashlyticsUncaughtExceptionHandler.writeFatal(CrashlyticsUncaughtExceptionHandler.java:803)
10-16 12:12:57.562 E/CrashlyticsCore(17187): 	at com.crashlytics.android.core.CrashlyticsUncaughtExceptionHandler.handleUncaughtException(CrashlyticsUncaughtExceptionHandler.java:271)
10-16 12:12:57.562 E/CrashlyticsCore(17187): 	at com.crashlytics.android.core.CrashlyticsUncaughtExceptionHandler.access$100(CrashlyticsUncaughtExceptionHandler.java:55)
10-16 12:12:57.562 E/CrashlyticsCore(17187): 	at com.crashlytics.android.core.CrashlyticsUncaughtExceptionHandler$5.call(CrashlyticsUncaughtExceptionHandler.java:247)
10-16 12:12:57.562 E/CrashlyticsCore(17187): 	at com.crashlytics.android.core.CrashlyticsUncaughtExceptionHandler$5.call(CrashlyticsUncaughtExceptionHandler.java:244)
10-16 12:12:57.562 E/CrashlyticsCore(17187): 	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
10-16 12:12:57.562 E/CrashlyticsCore(17187): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
10-16 12:12:57.562 E/CrashlyticsCore(17187): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
10-16 12:12:57.562 E/CrashlyticsCore(17187): 	at io.fabric.sdk.android.services.common.ExecutorUtils$1$1.onRun(ExecutorUtils.java:75)
10-16 12:12:57.562 E/CrashlyticsCore(17187): 	at io.fabric.sdk.android.services.common.BackgroundPriorityRunnable.run(BackgroundPriorityRunnable.java:30)
10-16 12:12:57.562 E/CrashlyticsCore(17187): 	at java.lang.Thread.run(Thread.java:818)
10-16 12:12:57.562 D/CrashlyticsCore(17187): Closing open sessions.
10-16 12:12:57.562 D/CrashlyticsCore(17187): Closing session: 59E4942F0396-0001-4323-CBD3347C1A6D
10-16 12:12:57.562 D/CrashlyticsCore(17187): Collecting session parts for ID 59E4942F0396-0001-4323-CBD3347C1A6D
10-16 12:12:57.562 D/CrashlyticsCore(17187): Session 59E4942F0396-0001-4323-CBD3347C1A6D has fatal exception: false
10-16 12:12:57.572 D/CrashlyticsCore(17187): Session 59E4942F0396-0001-4323-CBD3347C1A6D has non-fatal exceptions: false
10-16 12:12:57.572 D/CrashlyticsCore(17187): No events present for session ID 59E4942F0396-0001-4323-CBD3347C1A6D
10-16 12:12:57.572 D/CrashlyticsCore(17187): Removing session part files for ID 59E4942F0396-0001-4323-CBD3347C1A6D
10-16 12:12:57.572 D/CrashlyticsCore(17187): Opening an new session with ID 59E494390248-0002-4323-CBD3347C1A6D
10-16 12:12:57.582 D/Beta    (17187): Beta device token present: false
10-16 12:12:57.582 D/CrashlyticsCore(17187): Crashlytics completed exception processing. Invoking default exception handler.

**Comment by drungrin** [comment]
Fabric is deprecated and will be available until March 31, 2020. This project is also deprecated.
