### ISSUE TITLE
Library Support

### ISSUE THREAD

**Issue by alexshikov** [drungrin/Fabric.Sdk.Xamarin#49]
Hey @drungrin! Shout out for this great library!

I'm curious are you planning to update the NuGets? There are seems new versions of the Fabric SDK are out and it would be great to understand are there any coming updates? And does it make sense to spend time for PR's?

BTW, I've found a great article on automation of **com.crashlytics.android.build_id** generation for Xamarin.Android project: https://lucianpantelimon.info/uploading-xamarin-android-builds-to-fabric-io-beta/

**Comment by drungrin** [comment]
Great article. I’ll update the bindings in the next weeks. Can you help us with the automation? 

Enviado do seu iPhone

Em 2 de nov de 2017, à(s) 19:02, Alexey Shikov <notifications@github.com> escreveu:

**Comment by alexshikov** [comment]
Awesome!

Sure. I'm just setting up the scripts.
I'll share scripts when I finish and test them.

**Comment by MatFillion** [comment]
The Fabric SDK 1.4 allows the usage of Crashlytics integrated into Firebase, which I believe is going to be a very popular option from now on.

https://docs.fabric.io/android/changelog.html 
https://firebase.google.com/docs/crashlytics

**Comment by alexshikov** [comment]
@drungrin It's been a while :)
Would be great to update the library.
What are the chances you have some time to update the lib?
Or at least assist with PR (maybe describe some basic steps on what you usually doing for that).

P.S.: I'm about to send PR with auto-generation of **com.crashlytics.android.build_id**

**Comment by alexshikov** [comment]
@drungrin I noticed **release/1.5** branch. Any plans to release it to NuGet?

BTW, as promised #55

**Comment by nhdanh** [comment]
when you release on NUget ?

**Comment by nhdanh** [comment]
@alexshikov  Can you update you request to nuget. I look forward to new version from nuget

**Comment by alexshikov** [comment]
@nhdanh unfortunately, I can't release to NuGet this project. Seems only @drungrin can do that.

**Comment by drungrin** [comment]
Fabric is deprecated and will be available until March 31, 2020. This project is also deprecated.
