### ISSUE TITLE
Any Answers event causes NullReferenceException crash on Android, iOS works

### ISSUE THREAD

**Issue by chrismerron** [drungrin/Fabric.Sdk.Xamarin#53]
Any logging event I use in the Answers Kit returns the following error with a crash:
System.NullReferenceException: Object reference not set to an instance of an object

This only happens on Android, iOS is working fine

Both Answers and Crashlytics have been initialised in the main activity and I've tried the following and all causing crashes:

>  Answers.Instance.LogCustom("test");

> Answers.Instance.LogCustom("test", null);

>  Answers.Instance.LogLogin("login", true);

> Dictionary<string, object> attributes = new Dictionary<string, object>();
> attributes.Add("test", "test");
> Answers.Instance.LogCustom("test", attributes);

**Comment by drungrin** [comment]
Fabric is deprecated and will be available until March 31, 2020. This project is also deprecated.
