### ISSUE TITLE
Question about binaries

### ISSUE THREAD

**Issue by gilles-leblanc** [drungrin/Fabric.Sdk.Xamarin#54]
Hi, 

I'm looking into using these packages for Fabric and Crashlytics and I have some questions. I've made a test solution (which works) and looked a bit at the code in the repository.

I have some general questions that I need to answer to get this approved internally in the project I am using and was wondering if you could help me.

Are the NuGet packages essentially bindings to call the Fabric executables?

There seems to be a number of binary files in the solution. Are those copies of the Crashlytics files you would use when writing a native app for Android or iOS? 

If the project is reusing Fabric binaries, is there any method to verify the files haven't been tampered with? Sorry for this last question, but since the project handles sensitive information I must ask.

Thanks and I hope you're not offended by the last question ;)

**Comment by drungrin** [comment]
They are copies. You can use the original ones from any trusted source. Just make sure that they are the same version as the ones on the repository.
