### ISSUE TITLE
Xamarin Forms : Can't get crash details for iOS. 

### ISSUE THREAD

**Issue by vivekshah-zymr** [drungrin/Fabric.Sdk.Xamarin#56]
I am implementing Fabric crashlytics for my cross-platform project in xamarin forms.
As per instruction I followed the steps and the Android crash report is working fine, but for iOS, it's not.

I have initialized Crashlytics and Fabric in AppDelegate.cs and added a key in info.plist. The only part which is different than the XCode is run a script in the build phase. But for Xarmin forms in VS, there is no such part.
And in the dashboard, I am getting crash details like below.
`Found 1 unsymbolicated crashes from missing dSYMs in 1 version in the last 24 hours. Click to view details`
<img width="1014" alt="screen shot 2018-07-05 at 3 54 39 pm" src="https://user-images.githubusercontent.com/26891421/42318199-eec7560e-806b-11e8-8e70-3af484bd9269.png">

So I manually upload the zip file which contains the dSYM file. But it again gives the error like below.
`We're processing the uploaded dSYM(s). Please check back in a few minutes for the status.`
But nothing gets updated even after that. And when I refresh a page, it again asks for a dSYM file.

<img width="768" alt="screen shot 2018-07-05 at 3 57 58 pm" src="https://user-images.githubusercontent.com/26891421/42318326-4773000a-806c-11e8-9225-bf4bb4eaf3f2.png">

Can anyone help me in this?

**Comment by drungrin** [comment]
Fabric is deprecated and will be available until March 31, 2020. This project is also deprecated.
