### ISSUE TITLE
Crash on Android when using Fabric

### ISSUE THREAD

**Issue by nhdanh** [drungrin/Fabric.Sdk.Xamarin#57]
I am using Fabrics SDK for my app. On IOS it work fine. So on my android, my app starting and crash. 

I am debugged and discover. When I add Fabric.Instance.Initialize(Context). My app is crash. I remove this line. It work fine.

I go to dashboard of fabric and see a log. 

`
Fatal Exception: java.lang.Throwable
Cannot access a disposed object. Object name: 'System.Net.Sockets.Socket'.
System.Net.Sockets.Socket.ThrowIfDisposedAndClosed () (filename unknown)
System.Net.Sockets.Socket.EndConnect (System.IAsyncResult asyncResult) (filename unknown)
System.Net.Sockets.TcpClient.EndConnect (System.IAsyncResult asyncResult) (filename unknown)
System.Threading.Tasks.TaskFactory`1[TResult].FromAsyncCoreLogic (System.IAsyncResult iar, System.Func`2[T,TResult] endFunction, System.Action`1[T] endAction, System.Threading.Tasks.Task`1[TResult] promise, System.Boolean requiresSynchronization) (filename unknown)
`

And when you release a new version of this SDK. I see Crashlytics has 2.9.4 version.

**Comment by drungrin** [comment]
Fabric is deprecated and will be available until March 31, 2020. This project is also deprecated.
