### ISSUE TITLE
PROGUARD issue with 1.5

### ISSUE THREAD

**Issue by jahmai-ca** [drungrin/Fabric.Sdk.Xamarin#58]
The following compilation error occurs with 1.5.0, but not 1.4.0:

1>"C:\Repository\Projects\criticalarc\criticalarc\Source\Applications\Android\SafeZoneApp\SafeZoneApp.csproj" (default target) (1) ->
1>(_CompileToDalvikWithDx target) -> 
1>  PROGUARD : warning : com.crashlytics.android.core.CrashlyticsController: can't find referenced method 'java.lang.String getDeviceUUID()' in program class io.fabric.sdk.android.services.common.IdManager
1>  PROGUARD : warning : there were 1 unresolved references to program class members.

Using reflection, there doesn't appear to be any such method getDeviceUUID() on IdManager of FabricSDK 1.5.0.

**Comment by drungrin** [comment]
Fabric is deprecated and will be available until March 31, 2020. This project is also deprecated.
