### ISSUE TITLE
End of Life

### ISSUE THREAD

**Issue by fmliane** [drungrin/Fabric.Sdk.Xamarin#60]
Hi 

I've been monitoring my nugets packages, I just wanted to know when is the end of life for AndroidHTTP v1.0.0 and Answers v1.5.0. This is purely for documentation purpose, so that I will know when do I have to update or if there are no more support for my app. 

This can be a big help for maintenance. 
Thanks!

**Comment by drungrin** [comment]
Fabric is deprecated and will be available until March 31, 2020, so this is the deadline. I personally don't like Google Analytics and already migrated all my projects to Visual Studio App Center.
