### ISSUE TITLE
Have this issue of Duplicate Java

### ISSUE THREAD

**Issue by MakarkinPRO** [drungrin/Fabric.Sdk.Xamarin#9]
Have this issue:

Duplicate Java type found! Mappings between managed types and Java types must be unique. First Type: ‘IO.Fabric.Sdk.Android.Services.Events.IEventsStorageListenerImplementor, Fabric, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null’; Second Type: ‘Bindings.FabricSdk.Services.Events.IEventsStorageListenerImplementor, FabricSdk.Platform, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null’ Fabric Demo

**Comment by drungrin** [comment]
Can you share a project that has this issue?

**Comment by MakarkinPRO** [comment]
Now it's okay, just neede to delete "Fabric" link.

**Comment by vralfy** [comment]
Could you tell me exact what you did to resolve this issue?
